spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

logging:
  level:
    root: DEBUG
    com.government.payroll: TRACE
